default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: chat_server_development

test:
  <<: *default
  database: chat_server_test

production:
  <<: *default
  database: chat_server_production
  username: chat_server
  password: <%= ENV['CHAT_SERVER_DATABASE_PASSWORD'] %>
