default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: chat_server_development

test:
  <<: *default
  database: chat_server_test

production:
  <<: *default
  database: chat_server_production
  username: chat_server
  password: <%= ENV['CHAT_SERVER_DATABASE_PASSWORD'] %>
